name: Deploy Streamlit Dashboard

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace un push a la rama 'main'
  pull_request:
    branches:
      - main  # Se ejecuta cuando se hace un pull request hacia la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usar una m치quina virtual de Ubuntu

    steps:
    # Paso 1: Configurar Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Especifica la versi칩n de Python que deseas usar

    # Paso 2: Instalar dependencias directamente
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit matplotlib numpy pandas  # Instalaci칩n directa de las dependencias necesarias

    # Paso 3: Ejecutar la aplicaci칩n de Streamlit
    - name: Run Streamlit App
      run: |
        streamlit run app.py  # Asumiendo que tu archivo principal es 'app.py'
